In [2]:
import torch as t #GPU지원 텐서 패키지

In [3]:
te=t.tensor([0, 1, 2, 3, 4, 5, 6])
print(te) #tensor 출력
print(te.dim()) #rank, 차원
print(te.shape)
print(te.size()) #둘 다 shape 
print(te.dtype) #data type

tensor([0, 1, 2, 3, 4, 5, 6])
1
torch.Size([7])
torch.Size([7])
torch.int64


In [6]:
te=t.FloatTensor([0, 1, 2, 3, 4, 5, 6]) #DoubleT, LongT도 있어요

print(te[0], te[1])
print(te[2:5])
print(te[:3])
print(te.shape)

tensor(0.) tensor(1.)
tensor([2., 3., 4.])
tensor([0., 1., 2.])
torch.Size([7])


In [7]:
#2D Tensor
te2=t.FloatTensor([[1,2,3],
                      [4,5,6],
                      [7,8,9],
                      [10,11,12]])
print(te2)
print(te2.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


In [8]:
print(te2[0,1])
print(te2[0][1])

tensor(2.)
tensor(2.)


In [9]:
print(te2[:,1])
print(te2[:,1].size())
print(te2[:][1])
print(te2[:][1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([4., 5., 6.])
torch.Size([3])


In [10]:
print(te2[:,:-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [21]:
#텐서끼리 사칙연산은 shape이 같아야해
m1=t.FloatTensor([[3,3]])
m2=t.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [22]:
#broadcasting 크기가 다른 텐서끼리 사칙연산하게 텐서 크기 맞추고 값 복사해서 채워 넣기
#그냥 큰쪽으로 맞춰지겠지뭐
#vector+scalar
m1=t.FloatTensor([[1,2]])
m2=t.FloatTensor([3]) # 이게 [3,3] 으로
print(m1+m2)

tensor([[4., 5.]])


In [23]:
m1=t.FloatTensor([[1,2]])
m2=t.FloatTensor([[3],
                  [4]]) # 둘다 2x2로 바뀌는거야
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [24]:
#element-wise multiplecation
m1=t.FloatTensor([[1,2],[3,4]])
m2=t.FloatTensor([[4,5],[6,7]])
print(m1*m2)
print(m1.mul(m2))

tensor([[ 4., 10.],
        [18., 28.]])
tensor([[ 4., 10.],
        [18., 28.]])


In [25]:
#matrix multiplication
m1=t.FloatTensor([[1,2],[3,4]])
m2=t.FloatTensor([[1],[2]])
print(m1.shape)
print(m2.shape)
print(m1.matmul(m2)) #2x1 행렬곱은 교환법칙 적용안되는 것 기억나니

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [29]:
#평균 구하기
m=t.FloatTensor([[1,2,3],[4,5,6]])
print(m.mean()) #스칼라 값이 기본
print(m.mean().item()) #파이썬 변수형태로 바꾸기 ~

print(m.mean(dim=0)) # 해당 차원에서 평균값을 구하고 해당 차원 사라짐 >0이면 행 사라지고 1이면 열 사라지고
print(m.mean(dim=1))
print(m.mean(dim=-1))

tensor(3.5000)
3.5
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor([2., 5.])


In [30]:
#sum 도 똑같아 ~
print(m.sum())
print(m.sum(dim=0))
print(m.sum(dim=1))

tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])


In [32]:
#max
print(m.max())
print(m.max(dim=0)) #인덱스 정보도 반환
print(m.max(dim=0)[1]) #최대값, 인덱스값 따로;[0]이면 value [1]이면 indices

tensor(6.)
torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
tensor([1, 1, 1])


In [36]:
#view: 텐서 요소 유지하며 모양 바꾸기; 원소 개수 유지되어야하니까.
tt=t.FloatTensor([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(tt.shape)
print(tt.view(3,4))
print(tt.view(2,1,6))
print(tt.view(-1,3)) #-1쓰면 파이토치가 알아서 크기맞춤

torch.Size([4, 3])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10., 11.]]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [38]:
#squeeze 크기가 1인 차원은 모두 제거
ft=t.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [39]:
#unsqueeze() 입력받은 인덱스에 크기가 1인 차원 추가
ft=t.Tensor([0,1,2])
print(ft)
print(ft.shape)

print(ft.unsqueeze(0)) #0은 첫번째 차원
print(ft.unsqueeze(0).shape)
#view squeeze unsqeeuze 모두 요소 유지하면서 shape 바꾸는거네

tensor([0., 1., 2.])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [41]:
#type casting
lt=t.LongTensor([1,2,3,4])
print(lt)

print(lt.float()) # 텐서 타입 바꾸기
print(lt.double())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.], dtype=torch.float64)


In [42]:
#concatenate 텐서 연결, dim 통해서 어떤 인덱스인지 알려줘야됑
x=t.FloatTensor([[1,2],[3,4]])
y=t.FloatTensor([[5,6],[7,8]])

print(t.cat([x,y], dim=0))
print(t.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [43]:
#ones_like, zeros_like 똑같은 shape이면서 1,0으로 채워진 텐서 생성
x=t.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print(t.ones_like(x))
print(t.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [44]:
#ones, zeros는 텐서 새로 생성
print(t.ones(2,3))
print(t.zeros(3,2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
#텐서를 정규화하기 (0~1)
def normalize(tt):
  result=(tt-tt.min())/(tt.max()-tt.min())
  return result


fl=t.FloatTensor([[-3.2,1.3,123.5],[0.2,-5.2,16.9]])
print(fl)
print(normalize(fl))

tensor([[ -3.2000,   1.3000, 123.5000],
        [  0.2000,  -5.2000,  16.9000]])
tensor([[0.0155, 0.0505, 1.0000],
        [0.0420, 0.0000, 0.1717]])


In [7]:
#thresholding 
def thresholding(tt, threshold, value):
  origin_shape=tt.shape
  result=tt[:]
  result=result.view(-1)
  for i in range(result.shape[0]):
    if result[i]<=threshold:
      result[i]=value
    result=result.view(origin_shape)
    return result

fl=t.FloatTensor([[-3.2,1.3,123.5],[0.2,-5.2,16.9]])
print(thresholding(fl,-3,-100))
print(thresholding(fl,1.3, 0))

tensor([[-100.0000,    1.3000,  123.5000],
        [   0.2000,   -5.2000,   16.9000]])
tensor([[  0.0000,   1.3000, 123.5000],
        [  0.2000,  -5.2000,  16.9000]])


In [8]:
import os as os
os.getcwd()

'/content'